import FormLoginUser from '@/components/login-user'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}
export default function Login() {
  return (
    <>
      <FormLoginUser />
    </>
  )
}
