import FormLoginUser from '@/components/login-user'
import type { Metadata } from 'next'
import logoPng from 'public/logo.png'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from '@/components/navbar'
export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}
export default function Login() {
  return (
    <>
      <div className='w-full md:w-3/5 lg:w-2/5 mt-5 p-4 font-inter inline-block'>
        <div className='border rounded-md border-[#e7e8ec] shadow-md'>
          <Link
            href='/'
            className=' items-center justify-center gap-1 mt-2 hidden md:flex'
          >
            <Image src={logoPng} alt='' className='h-6 w-6' />
            <span className='text-[#8B8E99] text-2xl'>Lynx</span>
          </Link>
          <FormLoginUser />
        </div>
      </div>
    </>
  )
}
