import FormRegister from '@/components/form-register'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'register',
  description: 'Generated by create next app',
}
export default function Register() {
  return (
    <>
      <FormRegister />
    </>
  )
}
